# Generated by Django 5.2.5 on 2025-09-01 14:47

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_book_author_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='language of the book', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.language'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='language_name_case_insensitive_unique', violation_error_message='A language with this name already exists.(case insensitive match)'),
        ),
    ]
